function exercise_14() {
  /* 

    Exercise 14

    Date Object
    
    1. Create a new `Date` object and assign it to the variable 'currentDate'. 
    2. Then log the 'currentDate' variable to the console to see the datetime string 
      generated by the `Date` object

  */

  // CODE IN THE OPEN LINES BELOW

  const currentDate = new Date();
  console.log("Current Date and Time: ", currentDate);

  // CODE IN THE OPEN LINES ABOVE
}
